#!/bin/sh

## 起動前に実行したいコマンドをここに追加します。

babel www/src/*.js > www/index.js

## wwwディレクトリの内容をChrome Appとして起動します。
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --load-and-launch-app=`pwd`/www
